apiVersion: v1
kind: ConfigMap
metadata:
  name: agent-liquidity
  namespace: kaspa
data:
  KASPLEX_GRAPH_NODE_URL: "https://api.thegraph.com/subgraphs/name/kasplex/kasplex"
  DEX_ROUTER: "0x47F80b6D7071B7738D6DD9d973D7515ce753e9d9"
  DEX_FACTORY: "0x6ae24bE63D0ae0AD4A1da85e07dB39DF17e21649"
  WKAS: "0xf40178040278E16c8813dB20a84119A605812FB3"
  VAULT_ADDRESS: "0x73687dfa0a525f13aECC45045570E4aD1F1f325E"
  API_BASE_URL: "https://api.kaspacom.com"
