apiVersion: v1
kind: Service
metadata:
  name: agent-liquidity
  namespace: kaspa
spec:
  selector:
    app: agent-liquidity
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
  type: ClusterIP
