/**
 * setup-100-wallets.ts
 *
 * Sets up on-chain lending positions for 100 deterministic wallets on Galleon testnet.
 * Reads profiles from data/lending-wallets-100.json (generated by generate-100-wallets.ts).
 * Derives private keys at runtime — NEVER logged or stored.
 *
 * For each wallet:
 *   1. Deployer sends 15 iKAS (native gas)
 *   2. Deployer mints required tokens (MintableERC20)
 *   3. Wallet approves Pool + supplies collateral
 *   4. Wallet enables collateral flag
 *   5. Wallet borrows if profile requires it
 *   6. Verify position via getUserAccountData
 *
 * Processes in batches of 5 to avoid nonce collisions.
 * Output: data/lending-positions-100.json
 *
 * Run: npx tsx scripts/setup-100-wallets.ts
 * ⚠️  DO NOT run this during normal development — it executes real on-chain TXs.
 */

import { config as dotenvConfig } from 'dotenv';
import { readFile, mkdir, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { keccak256, toUtf8Bytes, Wallet as EthersWallet } from 'ethers';
import {
  createPublicClient,
  createWalletClient,
  defineChain,
  formatUnits,
  http,
  parseEther,
  parseUnits,
  type Address,
  type Hex,
} from 'viem';
import { privateKeyToAccount } from 'viem/accounts';

dotenvConfig();

// ---------------------------------------------------------------------------
// Chain & network config
// ---------------------------------------------------------------------------

const RPC_URL = 'https://galleon-testnet.igralabs.com:8545';
const CHAIN_ID = 38836;
const GAS_PRICE = 2_000_000_000_000n; // 2 twei
const LEGACY_TX = {
  type: 'legacy' as const,
  gasPrice: GAS_PRICE,
  gas: 500_000n,
};
const NATIVE_GAS_AMOUNT = parseEther('15'); // 15 iKAS per wallet
const BATCH_SIZE = 5;
const VARIABLE_RATE_MODE = 2n; // uint256 → bigint
const REFERRAL_CODE = 0;      // uint16 → number
const BASE_CURRENCY_DECIMALS = 8;

const POOL_ADDRESS = '0xb265EA393A9297472628E21575AE5c7E6458A1F2' as const satisfies Address;
const ORACLE_ADDRESS = '0x5B83681E48f365cfD2A4Ee29E2B699e38e04EbD9' as const satisfies Address;

const DATA_DIR = resolve(process.cwd(), 'data');
const WALLETS_FILE = resolve(DATA_DIR, 'lending-wallets-100.json');
const POSITIONS_FILE = resolve(DATA_DIR, 'lending-positions-100.json');

const chain = defineChain({
  id: CHAIN_ID,
  name: 'Galleon Testnet',
  nativeCurrency: { name: 'iKAS', symbol: 'iKAS', decimals: 18 },
  rpcUrls: {
    default: { http: [RPC_URL] },
    public: { http: [RPC_URL] },
  },
});

// ---------------------------------------------------------------------------
// Token config
// ---------------------------------------------------------------------------

type TokenSymbol = 'WKAS' | 'USDC' | 'USDT' | 'DAI' | 'WETH' | 'WBTC';

type TokenConfig = {
  symbol: TokenSymbol;
  address: Address;
  decimals: number;
};

const TOKENS: Record<TokenSymbol, TokenConfig> = {
  WKAS: { symbol: 'WKAS', address: '0x394C68684F9AFCEb9b804531EF07a864E8081738', decimals: 18 },
  USDC: { symbol: 'USDC', address: '0xfEE6ee271c2fD76EdAd5De7B8177C3935799111A', decimals: 6 },
  USDT: { symbol: 'USDT', address: '0xb522AC3161D67b6Ed2e311E0036A2F49F903bcc7', decimals: 6 },
  DAI:  { symbol: 'DAI',  address: '0x2c680F22600A632c9291c2f1E3b070ED79c1168e', decimals: 18 },
  WETH: { symbol: 'WETH', address: '0x23A8E284A6193C1D6A51A7b34d047ae0b969D660', decimals: 18 },
  WBTC: { symbol: 'WBTC', address: '0x2429526815517B971d45B0899C3D67990A68BcD7', decimals: 8 },
};

// ---------------------------------------------------------------------------
// ABIs (inline — no JSON import needed)
// ---------------------------------------------------------------------------

const erc20Abi = [
  {
    type: 'function', name: 'mint', stateMutability: 'nonpayable',
    inputs: [{ name: 'account', type: 'address' }, { name: 'amount', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function', name: 'approve', stateMutability: 'nonpayable',
    inputs: [{ name: 'spender', type: 'address' }, { name: 'amount', type: 'uint256' }],
    outputs: [{ name: '', type: 'bool' }],
  },
  {
    type: 'function', name: 'balanceOf', stateMutability: 'view',
    inputs: [{ name: 'account', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const;

const poolAbi = [
  {
    type: 'function', name: 'supply', stateMutability: 'nonpayable',
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'onBehalfOf', type: 'address' },
      { name: 'referralCode', type: 'uint16' },
    ],
    outputs: [],
  },
  {
    type: 'function', name: 'borrow', stateMutability: 'nonpayable',
    inputs: [
      { name: 'asset', type: 'address' },
      { name: 'amount', type: 'uint256' },
      { name: 'interestRateMode', type: 'uint256' },
      { name: 'referralCode', type: 'uint16' },
      { name: 'onBehalfOf', type: 'address' },
    ],
    outputs: [],
  },
  {
    type: 'function', name: 'setUserUseReserveAsCollateral', stateMutability: 'nonpayable',
    inputs: [{ name: 'asset', type: 'address' }, { name: 'useAsCollateral', type: 'bool' }],
    outputs: [],
  },
  {
    type: 'function', name: 'getUserAccountData', stateMutability: 'view',
    inputs: [{ name: 'user', type: 'address' }],
    outputs: [
      { name: 'totalCollateralBase', type: 'uint256' },
      { name: 'totalDebtBase', type: 'uint256' },
      { name: 'availableBorrowsBase', type: 'uint256' },
      { name: 'currentLiquidationThreshold', type: 'uint256' },
      { name: 'ltv', type: 'uint256' },
      { name: 'healthFactor', type: 'uint256' },
    ],
  },
] as const;

const oracleAbi = [
  {
    type: 'function', name: 'getAssetPrice', stateMutability: 'view',
    inputs: [{ name: 'asset', type: 'address' }],
    outputs: [{ name: '', type: 'uint256' }],
  },
] as const;

// ---------------------------------------------------------------------------
// JSON types (matches lending-wallets-100.json)
// ---------------------------------------------------------------------------

type TokenAmount = { token: string; amount: string };
type BorrowSpec = { token: string; borrowPercent: number };
type WalletRecord = {
  index: number;
  address: string;
  role: string;
  profile: {
    collateral: TokenAmount[];
    borrows: BorrowSpec[];
    targetHF: number | null;
  };
};

type WalletPosition = {
  index: number;
  address: string;
  role: string;
  status: 'success' | 'failed' | 'skipped';
  error?: string;
  totalCollateralUsd: string;
  totalDebtUsd: string;
  availableBorrowsUsd: string;
  healthFactor: string;
  txHashes: string[];
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function requireDeployerKey(): Hex {
  const key = process.env.IGRA_DEPLOYER_KEY;
  if (!key) throw new Error('IGRA_DEPLOYER_KEY environment variable is required');
  return (key.startsWith('0x') ? key : `0x${key}`) as Hex;
}

/** Derive private key from deployer key + index. NEVER log this value. */
function derivePrivateKey(deployerKey: string, index: number): Hex {
  return keccak256(toUtf8Bytes(`${deployerKey}:${index}:0:lending-stress-v2`)) as Hex;
}

function resolveToken(symbol: string): TokenConfig {
  const t = TOKENS[symbol as TokenSymbol];
  if (!t) throw new Error(`Unknown token: ${symbol}`);
  return t;
}

function formatBaseUsd(value: bigint): string {
  return formatUnits(value, BASE_CURRENCY_DECIMALS);
}

function formatHF(value: bigint): string {
  return formatUnits(value, 18);
}

// Using 'any' for client types avoids viem's deeply-recursive generic instantiation
// (TS2589) while preserving all other type checks in this file.
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type PublicClient = any;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type WalletClientType = any;

async function waitTx(publicClient: PublicClient, hash: Hex): Promise<void> {
  await publicClient.waitForTransactionReceipt({ hash });
}

// ---------------------------------------------------------------------------
// Deployer operations
// ---------------------------------------------------------------------------

async function sendNativeGas(
  deployerClient: WalletClientType,
  publicClient: PublicClient,
  to: Address,
): Promise<Hex> {
  const hash = await deployerClient.sendTransaction({
    account: deployerClient.account!,
    chain,
    to,
    value: NATIVE_GAS_AMOUNT,
    ...LEGACY_TX,
  });
  await waitTx(publicClient, hash);
  return hash;
}

async function mintToken(
  deployerClient: WalletClientType,
  publicClient: PublicClient,
  token: TokenConfig,
  to: Address,
  amount: bigint,
): Promise<Hex> {
  const hash = await deployerClient.writeContract({
    account: deployerClient.account!,
    address: token.address,
    abi: erc20Abi,
    functionName: 'mint',
    args: [to, amount],
    chain,
    ...LEGACY_TX,
  });
  await waitTx(publicClient, hash);
  return hash;
}

// ---------------------------------------------------------------------------
// Wallet operations
// ---------------------------------------------------------------------------

async function approveAndSupply(
  walletClient: WalletClientType,
  publicClient: PublicClient,
  token: TokenConfig,
  amount: bigint,
): Promise<Hex[]> {
  const hashes: Hex[] = [];
  const walletAddr = walletClient.account!.address;

  // Approve Pool
  const approveHash = await walletClient.writeContract({
    account: walletClient.account!,
    address: token.address,
    abi: erc20Abi,
    functionName: 'approve',
    args: [POOL_ADDRESS, amount],
    chain,
    ...LEGACY_TX,
  });
  hashes.push(approveHash);
  await waitTx(publicClient, approveHash);

  // Supply
  const supplyHash = await walletClient.writeContract({
    account: walletClient.account!,
    address: POOL_ADDRESS,
    abi: poolAbi,
    functionName: 'supply',
    args: [token.address, amount, walletAddr, REFERRAL_CODE],
    chain,
    ...LEGACY_TX,
  });
  hashes.push(supplyHash);
  await waitTx(publicClient, supplyHash);

  // Enable as collateral
  const collateralHash = await walletClient.writeContract({
    account: walletClient.account!,
    address: POOL_ADDRESS,
    abi: poolAbi,
    functionName: 'setUserUseReserveAsCollateral',
    args: [token.address, true],
    chain,
    ...LEGACY_TX,
  });
  hashes.push(collateralHash);
  await waitTx(publicClient, collateralHash);

  return hashes;
}

async function borrowToken(
  walletClient: WalletClientType,
  publicClient: PublicClient,
  token: TokenConfig,
  amount: bigint,
): Promise<Hex> {
  const walletAddr = walletClient.account!.address;
  const hash = await walletClient.writeContract({
    account: walletClient.account!,
    address: POOL_ADDRESS,
    abi: poolAbi,
    functionName: 'borrow',
    args: [token.address, amount, VARIABLE_RATE_MODE, REFERRAL_CODE, walletAddr],
    chain,
    ...LEGACY_TX,
  });
  await waitTx(publicClient, hash);
  return hash;
}

async function getUserAccountData(
  publicClient: PublicClient,
  user: Address,
): Promise<{
  totalCollateralBase: bigint;
  totalDebtBase: bigint;
  availableBorrowsBase: bigint;
  currentLiquidationThreshold: bigint;
  ltv: bigint;
  healthFactor: bigint;
}> {
  const result = await publicClient.readContract({
    address: POOL_ADDRESS,
    abi: poolAbi,
    functionName: 'getUserAccountData',
    args: [user],
  }) as readonly [bigint, bigint, bigint, bigint, bigint, bigint];

  return {
    totalCollateralBase: result[0],
    totalDebtBase: result[1],
    availableBorrowsBase: result[2],
    currentLiquidationThreshold: result[3],
    ltv: result[4],
    healthFactor: result[5],
  };
}

async function getAssetPrice(
  publicClient: PublicClient,
  token: TokenConfig,
): Promise<bigint> {
  return await publicClient.readContract({
    address: ORACLE_ADDRESS,
    abi: oracleAbi,
    functionName: 'getAssetPrice',
    args: [token.address],
  }) as bigint;
}

/**
 * Convert a USD base-currency value to token units.
 * baseValue: USD value in base-currency units (8 decimals)
 * assetPrice: price from oracle (8 decimals, USD per token)
 * tokenDecimals: token's own decimal places
 */
function baseToTokenAmount(baseValue: bigint, assetPrice: bigint, tokenDecimals: number): bigint {
  if (baseValue <= 0n || assetPrice <= 0n) return 0n;
  return (baseValue * 10n ** BigInt(tokenDecimals)) / assetPrice;
}

// ---------------------------------------------------------------------------
// Process a single wallet
// ---------------------------------------------------------------------------

async function processWallet(
  wallet: WalletRecord,
  deployerKey: Hex,
  deployerClient: WalletClientType,
  publicClient: PublicClient,
): Promise<WalletPosition> {
  const txHashes: string[] = [];
  const walletAddr = wallet.address as Address;

  console.log(`\n[${wallet.index}/100] ${wallet.role} — ${walletAddr}`);

  try {
    // Step 1: Fund with native gas
    console.log(`  → Sending 15 iKAS gas...`);
    const gasHash = await sendNativeGas(deployerClient, publicClient, walletAddr);
    txHashes.push(gasHash);

    // Step 2: Mint collateral tokens (deployer)
    for (const col of wallet.profile.collateral) {
      const token = resolveToken(col.token);
      const amount = parseUnits(col.amount, token.decimals);
      console.log(`  → Minting ${col.amount} ${col.token} to wallet...`);
      const mintHash = await mintToken(deployerClient, publicClient, token, walletAddr, amount);
      txHashes.push(mintHash);
    }

    // Step 3: Create wallet client for this wallet (key derived at runtime)
    const privateKey = derivePrivateKey(deployerKey, wallet.index);
    const walletAccount = privateKeyToAccount(privateKey);
    const walletClient = createWalletClient({
      account: walletAccount,
      chain,
      transport: http(RPC_URL),
    });

    // Step 4: Approve + supply each collateral token
    for (const col of wallet.profile.collateral) {
      const token = resolveToken(col.token);
      const amount = parseUnits(col.amount, token.decimals);
      console.log(`  → Supplying ${col.amount} ${col.token}...`);
      const supplyHashes = await approveAndSupply(walletClient, publicClient, token, amount);
      txHashes.push(...supplyHashes);
    }

    // Step 5: Borrow if profile requires
    for (const borrow of wallet.profile.borrows) {
      const token = resolveToken(borrow.token);
      const accountData = await getUserAccountData(publicClient, walletAddr);

      if (accountData.availableBorrowsBase === 0n) {
        console.log(`  ⚠️  No borrow capacity for ${walletAddr}, skipping borrow`);
        continue;
      }

      const assetPrice = await getAssetPrice(publicClient, token);
      const targetBase = (accountData.availableBorrowsBase * BigInt(borrow.borrowPercent)) / 100n;
      const borrowAmount = baseToTokenAmount(targetBase, assetPrice, token.decimals);

      if (borrowAmount <= 0n) {
        console.log(`  ⚠️  Computed zero borrow amount for ${token.symbol}, skipping`);
        continue;
      }

      console.log(`  → Borrowing ${formatUnits(borrowAmount, token.decimals)} ${token.symbol} (${borrow.borrowPercent}% capacity)...`);
      const borrowHash = await borrowToken(walletClient, publicClient, token, borrowAmount);
      txHashes.push(borrowHash);
    }

    // Step 6: Verify final position
    const finalData = await getUserAccountData(publicClient, walletAddr);
    const hf = formatHF(finalData.healthFactor);
    const targetHF = wallet.profile.targetHF;

    console.log(`  ✅ HF=${hf}${targetHF ? ` (target: ~${targetHF})` : ''} | collateral=$${formatBaseUsd(finalData.totalCollateralBase)} | debt=$${formatBaseUsd(finalData.totalDebtBase)}`);

    return {
      index: wallet.index,
      address: wallet.address,
      role: wallet.role,
      status: 'success',
      totalCollateralUsd: formatBaseUsd(finalData.totalCollateralBase),
      totalDebtUsd: formatBaseUsd(finalData.totalDebtBase),
      availableBorrowsUsd: formatBaseUsd(finalData.availableBorrowsBase),
      healthFactor: hf,
      txHashes,
    };
  } catch (err) {
    const error = err instanceof Error ? err.message : String(err);
    console.error(`  ❌ Failed: ${error}`);
    return {
      index: wallet.index,
      address: wallet.address,
      role: wallet.role,
      status: 'failed',
      error,
      totalCollateralUsd: '0',
      totalDebtUsd: '0',
      availableBorrowsUsd: '0',
      healthFactor: '0',
      txHashes,
    };
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const deployerKey = requireDeployerKey();

  // Load wallet profiles
  const walletsRaw = await readFile(WALLETS_FILE, 'utf8');
  const wallets: WalletRecord[] = JSON.parse(walletsRaw);
  console.log(`Loaded ${wallets.length} wallet profiles from ${WALLETS_FILE}`);

  await mkdir(DATA_DIR, { recursive: true });

  const deployerAccount = privateKeyToAccount(deployerKey);
  console.log(`Deployer: ${deployerAccount.address}`);

  const publicClient = createPublicClient({ chain, transport: http(RPC_URL) });
  const deployerClient = createWalletClient({
    account: deployerAccount,
    chain,
    transport: http(RPC_URL),
  });

  // Check deployer native balance
  const deployerBalance = await publicClient.getBalance({ address: deployerAccount.address });
  console.log(`Deployer iKAS balance: ${formatUnits(deployerBalance, 18)}`);
  const estimatedGasCost = parseEther('15') * BigInt(wallets.length);
  if (deployerBalance < estimatedGasCost) {
    throw new Error(
      `Insufficient deployer balance. Need ~${formatUnits(estimatedGasCost, 18)} iKAS for gas funding alone.`,
    );
  }

  const positions: WalletPosition[] = [];

  // Process in batches to limit concurrent nonce pressure
  for (let i = 0; i < wallets.length; i += BATCH_SIZE) {
    const batch = wallets.slice(i, i + BATCH_SIZE);
    console.log(`\n=== Batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(wallets.length / BATCH_SIZE)} (wallets ${i + 1}–${i + batch.length}) ===`);

    // Process sequentially within each batch (deployer nonce must be sequential)
    for (const wallet of batch) {
      const position = await processWallet(wallet, deployerKey, deployerClient, publicClient);
      positions.push(position);
    }
  }

  // Write positions file
  const output = {
    timestamp: new Date().toISOString(),
    network: 'galleon-testnet',
    chainId: CHAIN_ID,
    poolAddress: POOL_ADDRESS,
    totalWallets: positions.length,
    successful: positions.filter(p => p.status === 'success').length,
    failed: positions.filter(p => p.status === 'failed').length,
    wallets: positions,
  };

  await writeFile(POSITIONS_FILE, `${JSON.stringify(output, null, 2)}\n`, 'utf8');

  // Final summary
  console.log('\n' + '='.repeat(60));
  console.log(`✅ Setup complete: ${output.successful}/${output.totalWallets} succeeded`);
  if (output.failed > 0) {
    console.log(`❌ ${output.failed} failed:`);
    for (const p of positions.filter(pos => pos.status === 'failed')) {
      console.log(`   ${p.index}. ${p.role} — ${p.error}`);
    }
  }
  console.log(`Positions saved → ${POSITIONS_FILE}`);
}

main().catch(error => {
  console.error('Setup failed:', error);
  process.exitCode = 1;
});
